# docker-compose.yml
version: '2.22'
services:
  redis:
    image: redis:alpine
    container_name: iob.redis
    environment:
        ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 6379:6379

  react:
    image: leandrolasnor/ruby:iob
    container_name: iob.react
    stdin_open: true
    tty: true
    command: sh
    ports:
      - 3001:3001
    depends_on:
      - api

  api:
    image: leandrolasnor/ruby:iob
    container_name: iob.api
    stdin_open: true
    tty: true
    command: sh
    ports:
      - 3000:3000
    depends_on:
      - redis
