---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/countries/map":
    get:
      summary: list country
      tags:
      - Countries
      security:
      - ApiKeyAuth: []
      responses:
        '200':
          description: successful
  "/auth/sign_in":
    post:
      summary: sign in with user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/auth":
    post:
      summary: create a user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - email
              - password
              - password_confirmation
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
