# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

FactoryBot.create(:country, name: 'Afeganistão', code: 'af')
FactoryBot.create(:country, name: 'África do Sul', code: 'za')
FactoryBot.create(:country, name: 'Albânia', code: 'al')
FactoryBot.create(:country, name: 'Alemanha', code: 'de')
FactoryBot.create(:country, name: 'Andorra', code: 'ad')
FactoryBot.create(:country, name: 'Angola', code: 'ao')
FactoryBot.create(:country, name: 'Antiga e Barbuda', code: 'ag')
FactoryBot.create(:country, name: 'Arábia Saudita', code: 'sa')
FactoryBot.create(:country, name: 'Argélia', code: 'dz')
FactoryBot.create(:country, name: 'Argentina', code: 'ar')
FactoryBot.create(:country, name: 'Arménia', code: 'am')
FactoryBot.create(:country, name: 'Austrália', code: 'au')
FactoryBot.create(:country, name: 'Áustria', code: 'at')
FactoryBot.create(:country, name: 'Azerbaijão', code: 'az')
FactoryBot.create(:country, name: 'Bahamas', code: 'bs')
FactoryBot.create(:country, name: 'Bangladexe', code: 'bd')
FactoryBot.create(:country, name: 'Barbados', code: 'bb')
FactoryBot.create(:country, name: 'Barém', code: 'bh')
FactoryBot.create(:country, name: 'Bélgica', code: 'be')
FactoryBot.create(:country, name: 'Belize', code: 'bz')
FactoryBot.create(:country, name: 'Benim', code: 'bj')
FactoryBot.create(:country, name: 'Bielorrússia', code: 'by')
FactoryBot.create(:country, name: 'Bolívia', code: 'bo')
FactoryBot.create(:country, name: 'Bósnia e Herzegovina', code: 'ba')
FactoryBot.create(:country, name: 'Botsuana', code: 'bw')
FactoryBot.create(:country, name: 'Brasil', code: 'br')
FactoryBot.create(:country, name: 'Brunei', code: 'bn')
FactoryBot.create(:country, name: 'Bulgária', code: 'bg')
FactoryBot.create(:country, name: 'Burquina Faso', code: 'bf')
FactoryBot.create(:country, name: 'Burúndi', code: 'bi')
FactoryBot.create(:country, name: 'Butão', code: 'bt')
FactoryBot.create(:country, name: 'Cabo Verde', code: 'cv')
FactoryBot.create(:country, name: 'Camarões', code: 'cm')
FactoryBot.create(:country, name: 'Camboja', code: 'kh')
FactoryBot.create(:country, name: 'Canadá', code: 'ca')
FactoryBot.create(:country, name: 'Catar', code: 'qa')
FactoryBot.create(:country, name: 'Cazaquistão', code: 'kz')
FactoryBot.create(:country, name: 'Chade', code: 'td')
FactoryBot.create(:country, name: 'Chile', code: 'cl')
FactoryBot.create(:country, name: 'China', code: 'cn')
FactoryBot.create(:country, name: 'Chipre', code: 'cy')
FactoryBot.create(:country, name: 'Colômbia', code: 'co')
FactoryBot.create(:country, name: 'Comores', code: 'km')
FactoryBot.create(:country, name: 'Congo-Brazzaville', code: 'cg')
FactoryBot.create(:country, name: 'Coreia do Norte', code: 'kp')
FactoryBot.create(:country, name: 'Coreia do Sul', code: 'kr')
FactoryBot.create(:country, name: 'Costa do Marfim', code: 'ci')
FactoryBot.create(:country, name: 'Costa Rica', code: 'cr')
FactoryBot.create(:country, name: 'Croácia', code: 'hr')
FactoryBot.create(:country, name: 'Cuaite', code: 'kw')
FactoryBot.create(:country, name: 'Cuba', code: 'cu')
FactoryBot.create(:country, name: 'Dinamarca', code: 'dk')
FactoryBot.create(:country, name: 'Dominica', code: 'dm')
FactoryBot.create(:country, name: 'Egito', code: 'eg')
FactoryBot.create(:country, name: 'Emirados Árabes Unidos', code: 'ae')
FactoryBot.create(:country, name: 'Equador', code: 'ec')
FactoryBot.create(:country, name: 'Eritreia', code: 'er')
FactoryBot.create(:country, name: 'Eslováquia', code: 'sk')
FactoryBot.create(:country, name: 'Eslovénia', code: 'si')
FactoryBot.create(:country, name: 'Espanha', code: 'es')
FactoryBot.create(:country, name: 'Essuatíni', code: 'sz')
FactoryBot.create(:country, name: 'Estado da Palestina', code: 'ps')
FactoryBot.create(:country, name: 'Estados Unidos', code: 'us')
FactoryBot.create(:country, name: 'Estónia', code: 'ee')
FactoryBot.create(:country, name: 'Etiópia', code: 'et')
FactoryBot.create(:country, name: 'Fiji', code: 'fj')
FactoryBot.create(:country, name: 'Filipinas', code: 'ph')
FactoryBot.create(:country, name: 'Finlândia', code: 'fi')
FactoryBot.create(:country, name: 'França', code: 'fr')
FactoryBot.create(:country, name: 'Gabão', code: 'ga')
FactoryBot.create(:country, name: 'Gâmbia', code: 'gm')
FactoryBot.create(:country, name: 'Gana', code: 'gh')
FactoryBot.create(:country, name: 'Geórgia', code: 'ge')
FactoryBot.create(:country, name: 'Granada', code: 'gd')
FactoryBot.create(:country, name: 'Grécia', code: 'gr')
FactoryBot.create(:country, name: 'Guatemala', code: 'gt')
FactoryBot.create(:country, name: 'Guiana', code: 'gy')
FactoryBot.create(:country, name: 'Guiné', code: 'gn')
FactoryBot.create(:country, name: 'Guiné Equatorial', code: 'gq')
FactoryBot.create(:country, name: 'Guiné-Bissau', code: 'gw')
FactoryBot.create(:country, name: 'Haiti', code: 'ht')
FactoryBot.create(:country, name: 'Honduras', code: 'hn')
FactoryBot.create(:country, name: 'Hungria', code: 'hu')
FactoryBot.create(:country, name: 'Iémen', code: 'ye')
FactoryBot.create(:country, name: 'Ilhas Marechal', code: 'mh')
FactoryBot.create(:country, name: 'Índia', code: 'in')
FactoryBot.create(:country, name: 'Indonésia', code: 'id')
FactoryBot.create(:country, name: 'Irão', code: 'ir')
FactoryBot.create(:country, name: 'Iraque', code: 'iq')
FactoryBot.create(:country, name: 'Irlanda', code: 'ie')
FactoryBot.create(:country, name: 'Islândia', code: 'is')
FactoryBot.create(:country, name: 'Israel', code: 'il')
FactoryBot.create(:country, name: 'Itália', code: 'it')
FactoryBot.create(:country, name: 'Jamaica', code: 'jm')
FactoryBot.create(:country, name: 'Japão', code: 'jp')
FactoryBot.create(:country, name: 'Jibuti', code: 'dj')
FactoryBot.create(:country, name: 'Jordânia', code: 'jo')
FactoryBot.create(:country, name: 'Laus', code: 'la')
FactoryBot.create(:country, name: 'Lesoto', code: 'ls')
FactoryBot.create(:country, name: 'Letónia', code: 'lv')
FactoryBot.create(:country, name: 'Líbano', code: 'lb')
FactoryBot.create(:country, name: 'Libéria', code: 'lr')
FactoryBot.create(:country, name: 'Líbia', code: 'ly')
FactoryBot.create(:country, name: 'Listenstaine', code: 'li')
FactoryBot.create(:country, name: 'Lituânia', code: 'lt')
FactoryBot.create(:country, name: 'Luxemburgo', code: 'lu')
FactoryBot.create(:country, name: 'Macedónia do Norte', code: 'mk')
FactoryBot.create(:country, name: 'Madagáscar', code: 'mg')
FactoryBot.create(:country, name: 'Malásia', code: 'my')
FactoryBot.create(:country, name: 'Maláui', code: 'mw')
FactoryBot.create(:country, name: 'Maldivas', code: 'mv')
FactoryBot.create(:country, name: 'Mali', code: 'ml')
FactoryBot.create(:country, name: 'Malta', code: 'mt')
FactoryBot.create(:country, name: 'Marrocos', code: 'ma')
FactoryBot.create(:country, name: 'Maurícia', code: 'mu')
FactoryBot.create(:country, name: 'Mauritânia', code: 'mr')
FactoryBot.create(:country, name: 'México', code: 'mx')
FactoryBot.create(:country, name: 'Mianmar', code: 'mm')
FactoryBot.create(:country, name: 'Micronésia', code: 'fm')
FactoryBot.create(:country, name: 'Moçambique', code: 'mz')
FactoryBot.create(:country, name: 'Moldávia', code: 'md')
FactoryBot.create(:country, name: 'Mónaco', code: 'mc')
FactoryBot.create(:country, name: 'Mongólia', code: 'mn')
FactoryBot.create(:country, name: 'Montenegro', code: 'me')
FactoryBot.create(:country, name: 'Namíbia', code: 'na')
FactoryBot.create(:country, name: 'Nauru', code: 'nr')
FactoryBot.create(:country, name: 'Nepal', code: 'np')
FactoryBot.create(:country, name: 'Nicarágua', code: 'ni')
FactoryBot.create(:country, name: 'Níger', code: 'ne')
FactoryBot.create(:country, name: 'Nigéria', code: 'ng')
FactoryBot.create(:country, name: 'Noruega', code: 'no')
FactoryBot.create(:country, name: 'Nova Zelândia', code: 'nz')
FactoryBot.create(:country, name: 'Omã', code: 'om')
FactoryBot.create(:country, name: 'Países Baixos', code: 'nl')
FactoryBot.create(:country, name: 'Palau', code: 'pw')
FactoryBot.create(:country, name: 'Panamá', code: 'pa')
FactoryBot.create(:country, name: 'Papua Nova Guiné', code: 'pg')
FactoryBot.create(:country, name: 'Paquistão', code: 'pk')
FactoryBot.create(:country, name: 'Paraguai', code: 'py')
FactoryBot.create(:country, name: 'Peru', code: 'pe')
FactoryBot.create(:country, name: 'Polónia', code: 'pl')
FactoryBot.create(:country, name: 'Portugal', code: 'pt')
FactoryBot.create(:country, name: 'Quénia', code: 'ke')
FactoryBot.create(:country, name: 'Quirguistão', code: 'kg')
FactoryBot.create(:country, name: 'Quiribáti', code: 'ki')
FactoryBot.create(:country, name: 'Reino Unido', code: 'gb')
FactoryBot.create(:country, name: 'República Centro-Africana', code: 'cf')
FactoryBot.create(:country, name: 'República Checa', code: 'cz')
FactoryBot.create(:country, name: 'República Democrática do Congo', code: 'cd')
FactoryBot.create(:country, name: 'República Dominicana', code: 'do')
FactoryBot.create(:country, name: 'Roménia', code: 'ro')
FactoryBot.create(:country, name: 'Ruanda', code: 'rw')
FactoryBot.create(:country, name: 'Rússia', code: 'ru')
FactoryBot.create(:country, name: 'Salomão', code: 'sb')
FactoryBot.create(:country, name: 'Salvador', code: 'sv')
FactoryBot.create(:country, name: 'Samoa', code: 'ws')
FactoryBot.create(:country, name: 'Santa Lúcia', code: 'lc')
FactoryBot.create(:country, name: 'São Cristóvão e Neves', code: 'kn')
FactoryBot.create(:country, name: 'São Marinho', code: 'sm')
FactoryBot.create(:country, name: 'São Tomé e Príncipe', code: 'st')
FactoryBot.create(:country, name: 'São Vicente e Granadinas', code: 'vc')
FactoryBot.create(:country, name: 'Seicheles', code: 'sc')
FactoryBot.create(:country, name: 'Senegal', code: 'sn')
FactoryBot.create(:country, name: 'Serra Leoa', code: 'sl')
FactoryBot.create(:country, name: 'Sérvia', code: 'rs')
FactoryBot.create(:country, name: 'Singapura', code: 'sg')
FactoryBot.create(:country, name: 'Síria', code: 'sy')
FactoryBot.create(:country, name: 'Somália', code: 'so')
FactoryBot.create(:country, name: 'Sri Lanca', code: 'lk')
FactoryBot.create(:country, name: 'Sudão', code: 'sd')
FactoryBot.create(:country, name: 'Sudão do Sul', code: 'ss')
FactoryBot.create(:country, name: 'Suécia', code: 'se')
FactoryBot.create(:country, name: 'Suíça', code: 'ch')
FactoryBot.create(:country, name: 'Suriname', code: 'sr')
FactoryBot.create(:country, name: 'Tailândia', code: 'th')
FactoryBot.create(:country, name: 'Taiuã', code: 'tw')
FactoryBot.create(:country, name: 'Tajiquistão', code: 'tj')
FactoryBot.create(:country, name: 'Tanzânia', code: 'tz')
FactoryBot.create(:country, name: 'Timor-Leste', code: 'tl')
FactoryBot.create(:country, name: 'Togo', code: 'tg')
FactoryBot.create(:country, name: 'Tonga', code: 'to')
FactoryBot.create(:country, name: 'Trindade e Tobago', code: 'tt')
FactoryBot.create(:country, name: 'Tunísia', code: 'tn')
FactoryBot.create(:country, name: 'Turcomenistão', code: 'tm')
FactoryBot.create(:country, name: 'Turquia', code: 'tr')
FactoryBot.create(:country, name: 'Tuvalu', code: 'tv')
FactoryBot.create(:country, name: 'Ucrânia', code: 'ua')
FactoryBot.create(:country, name: 'Uganda', code: 'ug')
FactoryBot.create(:country, name: 'Uruguai', code: 'uy')
FactoryBot.create(:country, name: 'Usbequistão', code: 'uz')
FactoryBot.create(:country, name: 'Vanuatu', code: 'vu')
FactoryBot.create(:country, name: 'Vaticano', code: 'va')
FactoryBot.create(:country, name: 'Venezuela', code: 've')
FactoryBot.create(:country, name: 'Vietname', code: 'vn')
FactoryBot.create(:country, name: 'Zâmbia', code: 'zm')
FactoryBot.create(:country, name: 'Zimbábue', code: 'zw')
